# documentation:
# Environments -> Environment secrets: https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context
# Environments -> Environment variables: https://docs.github.com/actions/learn-github-actions/contexts#vars-context
# Secrets in reusable workflows: https://colinsalmcorner.com/consuming-environment-secrets-in-reusable-workflows/
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true

name: Deploy (reusable workflow)

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      DOCKER_CONTAINER_NAME: pacos2-production
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE }}:latest
            docker stop ${DOCKER_CONTAINER_NAME} || true
            docker rm ${DOCKER_CONTAINER_NAME} || true
            docker run -i -t -d --restart=always --name=${DOCKER_CONTAINER_NAME} \
              -e Pacos__TelegramBotApiKey='${{ secrets.PACOS__TELEGRAMBOTAPIKEY }}' \
              -e Pacos__GoogleCloudApiKey='${{ secrets.PACOS__GOOGLECLOUDAPIKEY }}' \
              -e Pacos__AllowedChatIds__0='${{ secrets.PACOS__ALLOWEDCHATIDS__0 }}' \
              -e Pacos__AllowedChatIds__1='${{ secrets.PACOS__ALLOWEDCHATIDS__1 }}' \
              -e Pacos__AllowedChatIds__2='${{ secrets.PACOS__ALLOWEDCHATIDS__2 }}' \
              -e Pacos__AllowedChatIds__3='${{ secrets.PACOS__ALLOWEDCHATIDS__3 }}' \
              -e Pacos__AllowedLanguageCodes__0='${{ secrets.PACOS__ALLOWEDLANGUAGECODES__0 }}' \
              -e Pacos__AllowedLanguageCodes__1='${{ secrets.PACOS__ALLOWEDLANGUAGECODES__1 }}' \
              ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE }}:latest
