name: master branch - test, build, push, deploy

on:
  push:
    branches:
      - master

jobs:
  run_tests:
    name: Run tests
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit

  build_and_push:
    name: Build and push
    needs: run_tests
    uses: ./.github/workflows/build_and_push.yml
    secrets: inherit

  deploy:
    name: Deploy
    needs: build_and_push
    uses: ./.github/workflows/deploy_latest.yml
    secrets: inherit
